### PR TITLE
Index category URL fix

### PR DESCRIPTION
**Pull request by asp437**
In the template of `index.html` category URL for posts are broken.

I think it's better to use `url` field of category object instead of manual URL generation.

### CODE REVIEW

**Comment by coolapso** [comment]
Seems ok to me! Just to double check, have you tested it??

**Comment by asp437** [comment]
Yes, I tested it on my locally generated blog (unfortunately it not online yet, so you can't check it yourself).

**Comment by coolapso** [comment]
@asp437 hmmm .... I am a bit without time to test this stuff! anyway... seems ok to me. Merging! 

Thank you.

**Comment by asp437** [comment]
Thank you for merge.

By the way, there is an example of broken link generated without this patch at [https://blog.colacoweb.net/](https://blog.colacoweb.net/) which is mentioned in the readme file and your profile. The regeneration of HTML with this patch applied to the theme should fix the problem.

**Comment by coolapso** [comment]
No worries... I thank you for the help! 

Now that you mention, I have seen it! xD 
thank you!! =) need pull this to local and fix my blog! xD

**Pull request merged**
